### ISSUE TITLE
Intermediate ACI Labs - images

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/aci-learning-labs#8]
@jmcgill298 
Can you check the image paths in the labs.  At least in the intermediate-aci_aci-api lab there is a path error and the images aren't getting pulled correctly.  Looks like you've got "assets/images/" as the location of the images in the markdown, but the images are actually just in the "assets" folder.  

When we talk on Friday let's get you setup with the Learning Lab Previewer so that you can do this validation on your end directly..

Hank

**Comment by jmcgill298** [comment]
PR submitted to correct
